# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170307_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6807\u7b7e\u540d\u79f0'),
        ),
    ]
