# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag_name',
        ),
    ]
