# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170315_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag_name',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
